version: '2'

services: 
  mongo_db:
    container_name: mongo
    image: 'aashreys/mongo-auth'
    environment:
      - AUTH=yes 
      - MONGODB_ADMIN_USER=yacsdev
      - MONGODB_ADMIN_PASS=yacsdevpass
      - MONGODB_APPLICATION_DATABASE=YacsDB
      - MONGODB_APPLICATION_USER=yacsBI
      - MONGODB_APPLICATION_PASS=yacsBIpass
    ports:
      - "27017:27017"
    volumes:
      - ../:/usr/src

  python_env:
    container_name: python_env
    build: ../
    stdin_open: true
    tty: true
    depends_on:
      - mongo_db
    ports:
      - "8888:8888"
    volumes:
      - ../:/home/jovyan/work

  mongo_express:
    container_name: mongo_express
    image: 'mongo-express'
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_ADMINUSERNAME=yacsdev 
      - ME_CONFIG_MONGODB_ADMINPASSWORD=yacsdevpass 
      - ME_CONFIG_MONGODB_AUTH_DATABASE=YacsDB 
      - ME_CONFIG_MONGODB_AUTH_USERNAME=yacsBI 
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=yacsBIpass 
    depends_on:
      - mongo_db
    ports:
      - "8081:8081"  
