version: '3'

services: 
  mongo_db:
    container_name: mongo
    image: 'aashreys/mongo-auth'
    environment:
      - AUTH=yes 
      - MONGODB_ADMIN_USER=yacsdev
      - MONGODB_ADMIN_PASS=yacsdevpass
      - MONGODB_APPLICATION_DATABASE=YacsDB
      - MONGODB_APPLICATION_USER=yacsBI
      - MONGODB_APPLICATION_PASS=yacsBIpass
    ports:
      - "27017:27017"
    volumes:
      - ../:/usr/src


  python_env:
    container_name: python_env
    build: ../
    stdin_open: true
    tty: true
    depends_on:
      - mongo_db
    ports:
      - "8888:8888"
    volumes:
      - ../:/home/jovyan/work
